<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Grace" failures="0" tests="5" name="TestCases.PMI_TestCases.MRN_PDR_Test" time="163.575" errors="1" timestamp="2025-01-09T15:27:24 IST" skipped="0">
  <testcase classname="TestCases.PMI_TestCases.MRN_PDR_Test" name="mRN_PDR_TC1" time="73.559"/>
  <testcase classname="TestCases.PMI_TestCases.MRN_PDR_Test" name="mRN_PDR_TC1" time="0.141">
    <error message="Cannot invoke &quot;java.util.HashMap.get(Object)&quot; because &quot;testData&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because "testData" is null
at TestCases.PMI_TestCases.MRN_PDR_Test.mRN_PDR_TC1(MRN_PDR_Test.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- mRN_PDR_TC1 -->
  <testcase classname="TestCases.PMI_TestCases.MRN_PDR_Test" name="save_MedicalFile" time="30.748"/>
  <testcase classname="TestCases.PMI_TestCases.MRN_PDR_Test" name="patient_Death_Reg" time="47.064"/>
  <testcase classname="TestCases.PMI_TestCases.MRN_PDR_Test" name="cancel_Patient_Death" time="12.063"/>
</testsuite> <!-- TestCases.PMI_TestCases.MRN_PDR_Test -->
